# Uncomment this line to define a global platform for your project
# platform :ios, “7.0”

#target “RCPractice” do

platform :ios, '7.0'

pod 'ReactiveCocoa', '~> 2.5'

#end

#target "RCPracticeTests" do

#end